version: 2

project_name: test-release-oss

before:
  hooks:
    - '{{ if not .IsSnapshot }}just embed-chart {{ .Version }}{{ else }}echo "Skipping embed-chart"{{ end }}'
    - '{{ if not .IsSnapshot }}just clean-release{{ else }}echo "Skipping clean-release"{{ end }}'
    - '{{ if not .IsSnapshot }}just copy-assets{{ else }}echo "Skipping copy-assets"{{ end }}'
    - '{{ if not .IsSnapshot }}just generate-testapp-latest-images {{ .Version }}{{ else }}echo "Skipping generate-testapp-latest-images"{{ end }}'
    - '{{ if not .IsSnapshot }}just generate-testapp-optional-images {{ .Version }}{{ else }}echo "Skipping generate-testapp-optional-images"{{ end }}'
    - '{{ if not .IsSnapshot }}just generate-matrix-specific-images {{ .Version }}{{ else }}echo "Skipping generate-matrix-specific-images"{{ end }}'

source:
  format: tar.gz

builds:
  - id: testapp
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: testapp
    main: ./cmd/testapp
    dir: .
    flags:
      - -trimpath
      - -mod
      - vendor
    tags:
      - embed_chart
    ldflags:
      - -s -w
      - -X github.com/LoftLabs-Experiments/test-release-oss/pkg/telemetry.SyncerVersion={{.Version}}
      - -X github.com/LoftLabs-Experiments/test-release-oss/pkg/telemetry.telemetryPrivateKey={{ with index .Env "TELEMETRY_PRIVATE_KEY" }}{{ . }}{{ end }}

  - id: testctl
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    binary: testctl
    main: ./cmd/testctl
    dir: .
    flags:
      - -trimpath
      - -mod
      - vendor
    tags:
      - embed_chart
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X github.com/LoftLabs-Experiments/test-release-oss/pkg/telemetry.SyncerVersion={{.Version}}
      - -X github.com/LoftLabs-Experiments/test-release-oss/pkg/telemetry.telemetryPrivateKey={{ with index .Env "TELEMETRY_PRIVATE_KEY" }}{{ . }}{{ end }}

archives:
  - id: testctl_archives
    format: binary
    builds:
      - testctl
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    builds_info:
      group: root
      owner: root
  - id: syncer_archives
    format: binary
    builds:
      - testapp
    name_template: "syncer-{{ .Os }}-{{ .Arch }}"
    builds_info:
      group: root
      owner: root

sboms:
  - id: testapp_sbom
    artifacts: binary
    documents:
      - '{{ if eq .ArtifactName "testapp" }}syncer-{{ .Os }}-{{ .Arch }}.sbom{{ else }}{{ .ArtifactName }}.sbom{{ end }}'

checksum:
  name_template: "checksums.txt"
  extra_files:
    - glob: ./release/*
    - glob: ./chart/values.schema.json

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+
    artifacts: checksum

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  make_latest: false

  extra_files:
    - glob: ./chart/values.schema.json

brews:
  - name: testctl
    ids:
      - testctl_archives
    dependencies:
      - name: helm
      - name: kubernetes-cli
    repository:
      owner: LoftLabs-Experiments
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/LoftLabs-Experiments/test-release-oss
    license: Apache-2.0
    description: "Test release application for testing GitHub workflows"
    conflicts:
      - testctl
      - LoftLabs-Experiments/tap/testctl-experimental
    test: |
      help_output = "testctl root command"
      assert_match help_output, shell_output("#{bin}/testctl --help")
    commit_author:
      name: loft-bot
      email: 73976634+loft-bot@users.noreply.github.com
    skip_upload: auto
  - name: testctl-experimental
    ids:
      - testctl_archives
    dependencies:
      - name: helm
      - name: kubernetes-cli
    repository:
      owner: LoftLabs-Experiments
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/LoftLabs-Experiments/test-release-oss
    license: Apache-2.0
    description: "Test release application for testing GitHub workflows"
    conflicts:
      - testctl
      - LoftLabs-Experiments/tap/testctl
    test: |
      help_output = "testctl root command"
      assert_match help_output, shell_output("#{bin}/testctl --help")
    commit_author:
      name: loft-bot
      email: 73976634+loft-bot@users.noreply.github.com

dockers:
  # --- Test-release-oss images ---
  - image_templates:
      - ghcr.io/loftlabs-experiments/test-release-oss:{{ .Version }}-amd64
      - '{{ if eq .Prerelease "" }}ghcr.io/loftlabs-experiments/test-release-oss:latest-amd64{{ end }}'
      - '{{ if eq .Prerelease "" }}ghcr.io/loftlabs-experiments/test-release-oss:{{ .Major }}-amd64{{ end }}'
      - '{{ if eq .Prerelease "" }}ghcr.io/loftlabs-experiments/test-release-oss:{{ .Major }}.{{ .Minor }}-amd64{{ end }}'
    use: buildx
    dockerfile: Dockerfile.release
    ids:
      - testapp
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
      - ghcr.io/loftlabs-experiments/test-release-oss:{{ .Version }}-arm64v8
      - '{{ if eq .Prerelease "" }}ghcr.io/loftlabs-experiments/test-release-oss:latest-arm64v8{{ end }}'
      - '{{ if eq .Prerelease "" }}ghcr.io/loftlabs-experiments/test-release-oss:{{ .Major }}-arm64v8{{ end }}'
      - '{{ if eq .Prerelease "" }}ghcr.io/loftlabs-experiments/test-release-oss:{{ .Major }}.{{ .Minor }}-arm64v8{{ end }}'
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.release
    ids:
      - testapp
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  # --- Test-release-oss-cli images ---
  - image_templates:
      - ghcr.io/loftlabs-experiments/testctl:{{ .Version }}-amd64
      - '{{ if eq .Prerelease "" }}ghcr.io/loftlabs-experiments/testctl:latest-amd64{{ end }}'
      - '{{ if eq .Prerelease "" }}ghcr.io/loftlabs-experiments/testctl:{{ .Major }}-amd64{{ end }}'
      - '{{ if eq .Prerelease "" }}ghcr.io/loftlabs-experiments/testctl:{{ .Major }}.{{ .Minor }}-amd64{{ end }}'
    use: buildx
    dockerfile: Dockerfile.cli.release
    ids:
      - testctl
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - image_templates:
      - ghcr.io/loftlabs-experiments/testctl:{{ .Version }}-arm64v8
      - '{{ if eq .Prerelease "" }}ghcr.io/loftlabs-experiments/testctl:latest-arm64v8{{ end }}'
      - '{{ if eq .Prerelease "" }}ghcr.io/loftlabs-experiments/testctl:{{ .Major }}-arm64v8{{ end }}'
      - '{{ if eq .Prerelease "" }}ghcr.io/loftlabs-experiments/testctl:{{ .Major }}.{{ .Minor }}-arm64v8{{ end }}'
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.cli.release
    ids:
      - testctl
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  # --- Test-release-oss multi arch ---
  - name_template: ghcr.io/loftlabs-experiments/test-release-oss:{{ .Version }}
    image_templates:
      - ghcr.io/loftlabs-experiments/test-release-oss:{{ .Version }}-amd64
      - ghcr.io/loftlabs-experiments/test-release-oss:{{ .Version }}-arm64v8

  - name_template: ghcr.io/loftlabs-experiments/test-release-oss:latest
    image_templates:
      - ghcr.io/loftlabs-experiments/test-release-oss:latest-amd64
      - ghcr.io/loftlabs-experiments/test-release-oss:latest-arm64v8
    skip_push: auto

  - name_template: ghcr.io/loftlabs-experiments/test-release-oss:{{ .Major }}
    image_templates:
      - ghcr.io/loftlabs-experiments/test-release-oss:{{ .Major }}-amd64
      - ghcr.io/loftlabs-experiments/test-release-oss:{{ .Major }}-arm64v8
    skip_push: auto

  - name_template: ghcr.io/loftlabs-experiments/test-release-oss:{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/loftlabs-experiments/test-release-oss:{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/loftlabs-experiments/test-release-oss:{{ .Major }}.{{ .Minor }}-arm64v8
    skip_push: auto

  # --- Testctl multi arch ---
  - name_template: ghcr.io/loftlabs-experiments/testctl:{{ .Version }}
    image_templates:
      - ghcr.io/loftlabs-experiments/testctl:{{ .Version }}-amd64
      - ghcr.io/loftlabs-experiments/testctl:{{ .Version }}-arm64v8

  - name_template: ghcr.io/loftlabs-experiments/testctl:latest
    image_templates:
      - ghcr.io/loftlabs-experiments/testctl:latest-amd64
      - ghcr.io/loftlabs-experiments/testctl:latest-arm64v8
    skip_push: auto

  - name_template: ghcr.io/loftlabs-experiments/testctl:{{ .Major }}
    image_templates:
      - ghcr.io/loftlabs-experiments/testctl:{{ .Major }}-amd64
      - ghcr.io/loftlabs-experiments/testctl:{{ .Major }}-arm64v8
    skip_push: auto

  - name_template: ghcr.io/loftlabs-experiments/testctl:{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/loftlabs-experiments/testctl:{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/loftlabs-experiments/testctl:{{ .Major }}.{{ .Minor }}-arm64v8
    skip_push: auto

  - name_template: loftsh/testctl:{{ .Major }}
    image_templates:
      - loftsh/testctl:{{ .Major }}-amd64
      - loftsh/testctl:{{ .Major }}-arm64v8
    skip_push: auto

docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    artifacts: all
    args:
      - "sign"
      - "${artifact}"
      - "--yes" # needed on cosign 2.0.0+